// demos/svelte-demo/src/lib/components/ui/tabs/TabsContent.svelte
<script lang="ts">
  import { getContext } from "svelte";
  import { cn } from "$lib/utils";
  import type { HTMLAttributes } from "svelte/elements";

  interface Props extends HTMLAttributes<HTMLDivElement> {
    class?: string;
    ref?: HTMLDivElement | null;
    value: string;
  }

  let { class: className, ref = $bindable(null), value, children, ...restProps }: Props = $props();

  const tabs = getContext<{ activeTab: string; setActiveTab: (val: string) => void }>("tabs");

  const isActive = $derived(tabs.activeTab === value);
</script>

{#if isActive}
  <div
    bind:this={ref}
    role="tabpanel"
    data-state={isActive ? "active" : "inactive"}
    class={cn(
      "mt-2 ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2",
      className
    )}
    {...restProps}
  >
    {@render children?.()}
  </div>
{/if}

// demos/vue-demo/src/components/ui/tabs/TabsContent.vue
<script setup lang="ts">
import { ref, inject, computed } from 'vue';
import type { Ref } from 'vue';
import { cn } from '@/lib/utils';

interface Props {
  class?: string;
  value: string;
}

const props = defineProps<Props>();

const elementRef = ref<HTMLDivElement | null>(null);

const tabs = inject<{ activeTab: Ref<string>; setActiveTab: (val: string) => void }>('tabs')!;

const isActive = computed(() => tabs.activeTab.value === props.value);

defineExpose({ elementRef });
</script>

<template>
  <div
    v-if="isActive"
    ref="elementRef"
    role="tabpanel"
    :data-state="isActive ? 'active' : 'inactive'"
    :class="
      cn(
        'mt-2 ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2',
        props.class
      )
    "
    v-bind="$attrs"
  >
    <slot />
  </div>
</template>
