// demos/svelte-demo/src/lib/components/ui/tabs/Tabs.svelte
<script lang="ts">
  import { setContext } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";

  interface Props extends HTMLAttributes<HTMLDivElement> {
    class?: string;
    ref?: HTMLDivElement | null;
    defaultValue?: string;
    value?: string;
  }

  let { class: className, ref = $bindable(null), defaultValue, value, children, ...restProps }: Props = $props();

  let activeTab = $state(value || defaultValue || "");

  setContext("tabs", {
    get activeTab() { return activeTab; },
    setActiveTab: (val: string) => { activeTab = val; }
  });
</script>

<div bind:this={ref} class={className} data-value={activeTab} {...restProps}>
  {@render children?.()}
</div>

// demos/vue-demo/src/components/ui/tabs/Tabs.vue
<script setup lang="ts">
import { ref, provide, readonly } from 'vue';

interface Props {
  class?: string;
  defaultValue?: string;
  modelValue?: string;
}

const props = defineProps<Props>();
const elementRef = ref<HTMLDivElement | null>(null);

const activeTab = ref(props.modelValue || props.defaultValue || "");

provide('tabs', {
  activeTab: readonly(activeTab),
  setActiveTab: (val: string) => { activeTab.value = val; }
});

defineExpose({ elementRef });
</script>

<template>
  <div ref="elementRef" :class="props.class" :data-value="activeTab" v-bind="$attrs">
    <slot />
  </div>
</template>
