// demos/svelte-demo/src/lib/components/ui/AvatarFallback.svelte
<script lang="ts">
  export let className: string | undefined = undefined;
  $: mergedClass = $$props.class;
  import type { HTMLAttributes } from 'svelte/elements';
  import { cn } from '$lib/utils';

  let ref;
</script>

<span
  bind:this={ref}
  class={cn(
    'flex h-full w-full items-center justify-center rounded-full bg-muted',
    className
  )}
  {...$$restProps}><slot /></span
>

// demos/vue-demo/src/components/ui/avatar/AvatarFallback.vue
<script setup lang="ts">
import { ref } from 'vue';
import { cn } from '@/lib/utils';

interface Props {
  class?: string;
}

const props = defineProps<Props>();
const elementRef = ref<HTMLSpanElement | null>(null);
defineExpose({ elementRef });
</script>

<template>
  <span ref="elementRef" :class="cn('flex h-full w-full items-center justify-center rounded-full bg-muted', props.class)" v-bind="$attrs">
    <slot />
  </span>
</template>
