// demos/svelte-demo/src/lib/components/ui/AvatarImage.svelte
<script lang="ts">
  export let className: string | undefined = undefined;
  $: mergedClass = $$props.class;
  import type { HTMLAttributes } from 'svelte/elements';
  import { cn } from '$lib/utils';

  let ref;
</script>

<img
  bind:this={ref}
  class={cn('aspect-square h-full w-full', mergedClass || className)}
  {...$$restProps}
/>

// demos/vue-demo/src/components/ui/avatar/AvatarImage.vue
<script setup lang="ts">
import { ref } from 'vue';
import { cn } from '@/lib/utils';

interface Props {
  class?: string;
  src?: string;
  alt?: string;
}

const props = defineProps<Props>();
const elementRef = ref<HTMLImageElement | null>(null);
defineExpose({ elementRef });
</script>

<template>
  <img ref="elementRef" :class="cn('aspect-square h-full w-full', props.class)" :src="props.src" :alt="props.alt" v-bind="$attrs" />
</template>
