// demos/svelte-demo/src/lib/components/ui/avatar/AvatarImage.svelte
<script lang="ts">
  import { cn } from "$lib/utils";
  import type { HTMLImgAttributes } from "svelte/elements";

  interface Props extends HTMLImgAttributes {
    class?: string;
    ref?: HTMLImageElement | null;
  }

  let { class: className, ref = $bindable(null), ...restProps }: Props = $props();
</script>

<img bind:this={ref} class={cn("aspect-square h-full w-full", className)} {...restProps} />

// demos/vue-demo/src/components/ui/avatar/AvatarImage.vue
<script setup lang="ts">
import { ref } from 'vue';
import { cn } from '@/lib/utils';

interface Props {
  class?: string;
  src?: string;
  alt?: string;
}

const props = defineProps<Props>();
const elementRef = ref<HTMLImageElement | null>(null);
defineExpose({ elementRef });
</script>

<template>
  <img ref="elementRef" :class="cn('aspect-square h-full w-full', props.class)" :src="props.src" :alt="props.alt" v-bind="$attrs" />
</template>
