// demos/svelte-demo/src/lib/components/ui/AccordionItem.svelte
<script lang="ts">
  export let className: string | undefined = undefined;
  $: mergedClass = $$props.class;
  import type { HTMLAttributes } from 'svelte/elements';
  import { ChevronDown } from 'lucide-svelte';
  import { cn } from '$lib/utils';

  let ref;
</script>

<div
  bind:this={ref}
  class={cn('border-b', mergedClass || className)}
  {...$$restProps}
>
  <slot />
</div>

// demos/vue-demo/src/lib/components/ui/AccordionItem.vue
<template>
  <div ref="ref" :class="cn('border-b', className)" v-bind="$attrs">
    <slot></slot>
  </div>
</template>

<script setup lang="ts">
const { className } = defineProps({
  className: { type: String, default: undefined },
});
import { ChevronDown } from 'lucide-vue-next';
import { cn } from '@/lib/utils';
</script>
