// demos/svelte-demo/src/lib/components/ui/Badge.svelte
<script lang="ts">
  export let variant: string = 'default';
  export let className: string | undefined = undefined;
  $: mergedClass = $$props.class;
  import { cva } from 'class-variance-authority';
  import { cn } from '$lib/utils';
  const badgeVariants = cva(
    'inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2',
    {
      variants: {
        variant: {
          default:
            'border-transparent bg-primary text-primary-foreground hover:bg-primary/80',
          secondary:
            'border-transparent bg-secondary text-secondary-foreground hover:bg-secondary/80',
          destructive:
            'border-transparent bg-destructive text-destructive-foreground hover:bg-destructive/80',
          outline: 'text-foreground',
        },
      },
      defaultVariants: {
        variant: 'default',
      },
    }
  );
</script>

<div
  {...$$restProps}
  class={cn(
    badgeVariants({
      variant,
    }),
    className
  )}
>
  <slot />
</div>

// demos/vue-demo/src/lib/components/ui/Badge.vue
<template>
  <div
    :class="
      cn(
        badgeVariants({
          variant,
        }),
        className
      )
    "
    v-bind="$attrs"
  >
    <slot></slot>
  </div>
</template>

<script setup lang="ts">
const { variant, className } = defineProps({
  variant: { type: String, default: 'default' },
  className: { type: String, default: undefined },
});
import { cva } from 'class-variance-authority';
import { cn } from '@/lib/utils';
const badgeVariants = cva(
  'inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2',
  {
    variants: {
      variant: {
        default:
          'border-transparent bg-primary text-primary-foreground hover:bg-primary/80',
        secondary:
          'border-transparent bg-secondary text-secondary-foreground hover:bg-secondary/80',
        destructive:
          'border-transparent bg-destructive text-destructive-foreground hover:bg-destructive/80',
        outline: 'text-foreground',
      },
    },
    defaultVariants: {
      variant: 'default',
    },
  }
);
</script>
