// demos/svelte-demo/src/lib/components/ui/Card.svelte
<script lang="ts">
  export let className: string | undefined = undefined;
  $: mergedClass = $$props.class;
  import type { HTMLAttributes } from 'svelte/elements';
  import { cn } from '$lib/utils';

  let ref;
</script>

<div
  bind:this={ref}
  {...$$restProps}
  class={cn(
    'rounded-lg border bg-card text-card-foreground shadow-sm',
    className
  )}
>
  <slot />
</div>

// demos/vue-demo/src/lib/components/ui/Card.vue
<template>
  <div
    ref="ref"
    :class="
      cn('rounded-lg border bg-card text-card-foreground shadow-sm', className)
    "
    v-bind="$attrs"
  >
    <slot></slot>
  </div>
</template>

<script setup lang="ts">
const { className } = defineProps({
  className: { type: String, default: undefined },
});
import { cn } from '@/lib/utils';
</script>
