// demos/svelte-demo/src/lib/components/ui/CardFooter.svelte
<script lang="ts">
  export let className: string | undefined = undefined;
  $: mergedClass = $$props.class;
  import type { HTMLAttributes } from 'svelte/elements';
  import { cn } from '$lib/utils';

  let ref;
</script>

<div
  bind:this={ref}
  {...$$restProps}
  class={cn('flex items-center p-6 pt-0', mergedClass || className)}
>
  <slot />
</div>

// demos/vue-demo/src/lib/components/ui/CardFooter.vue
<template>
  <div
    ref="ref"
    :class="cn('flex items-center p-6 pt-0', className)"
    v-bind="$attrs"
  >
    <slot></slot>
  </div>
</template>

<script setup lang="ts">
const { className } = defineProps({
  className: { type: String, default: undefined },
});
import { cn } from '@/lib/utils';
</script>
