// demos/svelte-demo/src/lib/components/ui/TableBody.svelte
<script lang="ts">
  export let className: string | undefined = undefined;
  $: mergedClass = $$props.class;
  import type { HTMLAttributes } from 'svelte/elements';
  import { cn } from '$lib/utils';

  let ref;
</script>

<tbody
  bind:this={ref}
  {...$$restProps}
  class={cn('[&_tr:last-child]:border-0', mergedClass || className)}
  ><slot /></tbody
>

// demos/vue-demo/src/lib/components/ui/TableBody.vue
<template>
  <tbody
    ref="ref"
    :class="cn('[&_tr:last-child]:border-0', className)"
    v-bind="$attrs"
  >
    <slot></slot>
  </tbody>
</template>

<script setup lang="ts">
const { className } = defineProps({
  className: { type: String, default: undefined },
});
import { cn } from '@/lib/utils';
</script>
