// demos/svelte-demo/src/lib/components/ui/TableFooter.svelte
<script lang="ts">
  export let className: string | undefined = undefined;
  $: mergedClass = $$props.class;
  import type { HTMLAttributes } from 'svelte/elements';
  import { cn } from '$lib/utils';

  let ref;
</script>

<tfoot
  bind:this={ref}
  {...$$restProps}
  class={cn(
    'border-t bg-muted/50 font-medium [&>tr]:last:border-b-0',
    className
  )}
/>

// demos/vue-demo/src/lib/components/ui/TableFooter.vue
<template>
  <tfoot
    ref="ref"
    :class="
      cn('border-t bg-muted/50 font-medium [&>tr]:last:border-b-0', className)
    "
    v-bind="$attrs"
  ></tfoot>
</template>

<script setup lang="ts">
const { className } = defineProps({
  className: { type: String, default: undefined },
});
import { cn } from '@/lib/utils';
</script>
