// demos/svelte-demo/src/lib/components/ui/TableCaption.svelte
<script lang="ts">
  export let className: string | undefined = undefined;
  $: mergedClass = $$props.class;
  import type { HTMLAttributes } from 'svelte/elements';
  import { cn } from '$lib/utils';

  let ref;
</script>

<caption
  bind:this={ref}
  {...$$restProps}
  class={cn('mt-4 text-sm text-muted-foreground', mergedClass || className)}
  ><slot /></caption
>

// demos/vue-demo/src/lib/components/ui/TableCaption.vue
<template>
  <caption
    ref="ref"
    :class="cn('mt-4 text-sm text-muted-foreground', className)"
    v-bind="$attrs"
  >
    <slot></slot>
  </caption>
</template>

<script setup lang="ts">
const { className } = defineProps({
  className: { type: String, default: undefined },
});
import { cn } from '@/lib/utils';
</script>
