// demos/svelte-demo/src/lib/components/ui/TableHead.svelte
<script lang="ts">
  export let className: string | undefined = undefined;
  $: mergedClass = $$props.class;
  import type { HTMLAttributes } from 'svelte/elements';
  import { cn } from '$lib/utils';

  let ref;
</script>

<th
  bind:this={ref}
  {...$$restProps}
  class={cn(
    'h-12 px-4 text-left align-middle font-medium text-muted-foreground [&:has([role=checkbox])]:pr-0',
    className
  )}><slot /></th
>

// demos/vue-demo/src/lib/components/ui/TableHead.vue
<template>
  <th
    ref="ref"
    :class="
      cn(
        'h-12 px-4 text-left align-middle font-medium text-muted-foreground [&:has([role=checkbox])]:pr-0',
        className
      )
    "
    v-bind="$attrs"
  >
    <slot></slot>
  </th>
</template>

<script setup lang="ts">
const { className } = defineProps({
  className: { type: String, default: undefined },
});
import { cn } from '@/lib/utils';
</script>
