// demos/svelte-demo/src/lib/components/ui/avatar/Avatar.svelte
<script lang="ts">
  import { cn } from "$lib/utils";
  import type { HTMLAttributes } from "svelte/elements";

  interface Props extends HTMLAttributes<HTMLSpanElement> {
    class?: string;
    ref?: HTMLSpanElement | null;
  }

  let { class: className, ref = $bindable(null), children, ...restProps }: Props = $props();
</script>

<span bind:this={ref} class={cn("relative flex h-10 w-10 shrink-0 overflow-hidden rounded-full", className)} {...restProps}>
  {@render children?.()}
</span>

// demos/vue-demo/src/components/ui/Avatar.vue
<script setup lang="ts">
import { ref } from 'vue';
import { cn } from '@/lib/utils';

interface Props {
  class?: string;
}

const props = defineProps<Props>();

const elementRef = ref<HTMLSpanElement | null>(null);

defineExpose({ elementRef });
</script>

<template>
  <span
    ref="elementRef"
    :class="cn('relative flex h-10 w-10 shrink-0 overflow-hidden rounded-full', props.class)"
    v-bind="$attrs"
  >
    <slot />
  </span>
</template>
