// demos/svelte-demo/src/lib/components/ui/DialogTitle.svelte
<script lang="ts">
import { cn } from "$lib/utils";
import type { HTMLAttributes } from "svelte/elements";
import { X } from "lucide-svelte";

interface Props extends HTMLAttributes<HTMLHeadingElement> {
  class?: string;
  ref?: HTMLHeadingElement | null;
}

let { class: className, ref = $bindable(null), children, ...restProps }: Props = $props();
</script>

<h5 bind:this={ref} class={cn("text-lg font-semibold leading-none tracking-tight", className)} {...restProps}>
  {@render children?.()}
</h5>

// demos/vue-demo/src/components/ui/DialogTitle.vue
<script setup lang="ts">
import { ref } from 'vue';
import { cn } from '@/lib/utils';
// import { X } from 'lucide-vue-next'; // Not used in fallback template

interface Props {
  class?: string;
}

const props = defineProps<Props>();

const elementRef = ref<HTMLHeadingElement | null>(null);

defineExpose({ elementRef });
</script>

<template>
  <h5
    ref="elementRef"
    :class="cn('text-lg font-semibold leading-none tracking-tight', props.class)"
    v-bind="$attrs"
  >
    <slot />
  </h5>
</template>
