// demos/svelte-demo/src/lib/components/ui/Label.svelte
<script lang="ts">
import { cn } from "$lib/utils";
import { cva, type VariantProps } from "class-variance-authority";
import type { HTMLAttributes } from "svelte/elements";

const labelVariants = cva(
  "text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70",
  {
    variants: {
    },
    defaultVariants: {
    },
  }
);

interface Props extends HTMLAttributes<HTMLLabelElement>, VariantProps<typeof labelVariants> {
  class?: string;
  ref?: HTMLLabelElement | null;
}

let { class: className, ref = $bindable(null), children, ...restProps }: Props = $props();
</script>

<div bind:this={ref} class={cn(labelVariants({  }), className)} {...restProps}>
  {@render children?.()}
</div>

// demos/vue-demo/src/components/ui/Label.vue
<script setup lang="ts">
import { ref } from 'vue';
import { cn } from '@/lib/utils';
import { cva } from 'class-variance-authority';

const labelVariants = cva(
  'text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70',
  {
    variants: {},
    defaultVariants: {},
  }
);

interface Props {
  class?: string;
}

const props = defineProps<Props>();

const elementRef = ref<HTMLLabelElement | null>(null);

defineExpose({ elementRef });
</script>

<template>
  <div ref="elementRef" :class="cn(labelVariants({}), props.class)" v-bind="$attrs">
    <slot />
  </div>
</template>
