// demos/svelte-demo/src/lib/components/ui/Progress.svelte
<script lang="ts">
  import { cn } from '$lib/utils';
  import type { HTMLAttributes } from 'svelte/elements';

  interface Props extends HTMLAttributes<HTMLDivElement> {
    class?: string;
    ref?: HTMLDivElement | null;
  }

  let { class: className, ref = $bindable(null), children, ...restProps }: Props = $props();
</script>

<div
  bind:this={ref}
  class={cn('relative h-4 w-full overflow-hidden rounded-full bg-secondary', className)}
  {...restProps}
>
  {@render children?.()}
</div>

// demos/vue-demo/src/components/ui/Progress.vue
<script setup lang="ts">
import { ref } from 'vue';
import { cn } from '@/lib/utils';

interface Props {
  class?: string;
}

const props = defineProps<Props>();

const elementRef = ref<HTMLDivElement | null>(null);

defineExpose({ elementRef });
</script>

<template>
  <div
    ref="elementRef"
    :class="cn('relative h-4 w-full overflow-hidden rounded-full bg-secondary', props.class)"
    v-bind="$attrs"
  >
    <slot />
  </div>
</template>
