// demos/vue-demo/src/components/ui/table/Table.vue
<script setup lang="ts">
import { ref } from 'vue';
import { cn } from '@/lib/utils';

interface Props {
  class?: string;
}

const props = defineProps<Props>();
const elementRef = ref<HTMLTableElement | null>(null);
defineExpose({ elementRef });
</script>

<template>
  <div class="relative w-full overflow-auto">
    <table ref="elementRef" :class="cn('w-full caption-bottom text-sm', props.class)" v-bind="$attrs">
      <slot />
    </table>
  </div>
</template>

// demos/svelte-demo/src/lib/components/ui/table/Table.svelte
<script lang="ts">
  import { cn } from "$lib/utils";
  import type { HTMLTableAttributes } from "svelte/elements";

  interface Props extends HTMLTableAttributes {
    class?: string;
    ref?: HTMLTableElement | null;
  }

  let { class: className, ref = $bindable(null), children, ...restProps }: Props = $props();
</script>

<div class="relative w-full overflow-auto">
  <table bind:this={ref} class={cn("w-full caption-bottom text-sm", className)} {...restProps}>
    {@render children?.()}
  </table>
</div>
