// demos/vue-demo/src/components/ui/table/TableRow.vue
<script setup lang="ts">
import { ref } from 'vue';
import { cn } from '@/lib/utils';

interface Props {
  class?: string;
}

const props = defineProps<Props>();
const elementRef = ref<HTMLTableRowElement | null>(null);
defineExpose({ elementRef });
</script>

<template>
  <tr ref="elementRef" :class="cn('border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted', props.class)" v-bind="$attrs">
    <slot />
  </tr>
</template>

// demos/svelte-demo/src/lib/components/ui/table/TableRow.svelte
<script lang="ts">
  import { cn } from "$lib/utils";
  import type { HTMLAttributes } from "svelte/elements";

  interface Props extends HTMLAttributes<HTMLTableRowElement> {
    class?: string;
    ref?: HTMLTableRowElement | null;
  }

  let { class: className, ref = $bindable(null), children, ...restProps }: Props = $props();
</script>

<tr bind:this={ref} class={cn("border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted", className)} {...restProps}>
  {@render children?.()}
</tr>
