// demos/vue-demo/src/components/ui/table/TableBody.vue
<script setup lang="ts">
import { ref } from 'vue';
import { cn } from '@/lib/utils';

interface Props {
  class?: string;
}

const props = defineProps<Props>();
const elementRef = ref<HTMLTableSectionElement | null>(null);
defineExpose({ elementRef });
</script>

<template>
  <tbody ref="elementRef" :class="cn('[&_tr:last-child]:border-0', props.class)" v-bind="$attrs">
    <slot />
  </tbody>
</template>

// demos/svelte-demo/src/lib/components/ui/table/TableBody.svelte
<script lang="ts">
  import { cn } from "$lib/utils";
  import type { HTMLAttributes } from "svelte/elements";

  interface Props extends HTMLAttributes<HTMLTableSectionElement> {
    class?: string;
    ref?: HTMLTableSectionElement | null;
  }

  let { class: className, ref = $bindable(null), children, ...restProps }: Props = $props();
</script>

<tbody bind:this={ref} class={cn("[&_tr:last-child]:border-0", className)} {...restProps}>
  {@render children?.()}
</tbody>
