// demos/vue-demo/src/components/ui/table/TableCell.vue
<script setup lang="ts">
import { ref } from 'vue';
import { cn } from '@/lib/utils';

interface Props {
  class?: string;
}

const props = defineProps<Props>();
const elementRef = ref<HTMLTableCellElement | null>(null);
defineExpose({ elementRef });
</script>

<template>
  <td ref="elementRef" :class="cn('p-4 align-middle [&:has([role=checkbox])]:pr-0', props.class)" v-bind="$attrs">
    <slot />
  </td>
</template>

// demos/svelte-demo/src/lib/components/ui/table/TableCell.svelte
<script lang="ts">
  import { cn } from "$lib/utils";
  import type { HTMLTdAttributes } from "svelte/elements";

  interface Props extends HTMLTdAttributes {
    class?: string;
    ref?: HTMLTableCellElement | null;
  }

  let { class: className, ref = $bindable(null), children, ...restProps }: Props = $props();
</script>

<td bind:this={ref} class={cn("p-4 align-middle [&:has([role=checkbox])]:pr-0", className)} {...restProps}>
  {@render children?.()}
</td>
