// demos/vue-demo/src/components/ui/alert/AlertTitle.vue
<script setup lang="ts">
import { ref } from 'vue';
import { cn } from '@/lib/utils';

interface Props {
  class?: string;
}

const props = defineProps<Props>();

const elementRef = ref<HTMLParagraphElement | null>(null);

defineExpose({ elementRef });
</script>

<template>
  <p
    ref="elementRef"
    :class="cn('mb-1 font-medium leading-none tracking-tight', props.class)"
    v-bind="$attrs"
  >
    <slot />
  </p>
</template>

// demos/svelte-demo/src/lib/components/ui/alert/AlertTitle.svelte
<script lang="ts">
import { cn } from "$lib/utils";
import type { HTMLAttributes } from "svelte/elements";

interface Props extends HTMLAttributes<HTMLParagraphElement> {
  class?: string;
  ref?: HTMLParagraphElement | null;
}

let { class: className, ref = $bindable(null), children, ...restProps }: Props = $props();
</script>

<p bind:this={ref} class={cn("mb-1 font-medium leading-none tracking-tight", className)} {...restProps}>
  {@render children?.()}
</p>
