// demos/vue-demo/src/lib/components/ui/AccordionTrigger.vue
<template>
  <h3 
    ><component
      ref="ref"
      :class="
        cn(
          'flex flex-1 items-center justify-between py-4 font-medium transition-all hover:underline [&[data-state=open]>svg]:rotate-180',
          className
        )
      "
      :is="AccordionPrimitive.Trigger"
      v-bind="$attrs"
      ><slot /><ChevronDown></ChevronDown></h3></component>
</template>

<script setup lang="ts">
const { className } = defineProps({
  className: { type: String, default: undefined }
});
import { ChevronDown } from 'lucide-vue-next';
import { cn } from "@/lib/utils";
</script>

// demos/svelte-demo/src/lib/components/ui/AccordionTrigger.svelte
<script lang="ts">
  export let className: string | undefined = undefined;
  $: mergedClass = $$props.class;
  import type { HTMLAttributes } from 'svelte/elements';
  import { ChevronDown } from 'lucide-svelte';
  import { cn } from '$lib/utils';

  let ref;
</script>

<h3 class="flex">
  <button
    bind:this={ref}
    class={cn(
      'flex flex-1 items-center justify-between py-4 font-medium transition-all hover:underline [&[data-state=open]>svg]:rotate-180',
      className
    )}
    {...$$restProps}
    >{@render children?.()}<ChevronDown
      class="h-4 w-4 shrink-0 transition-transform duration-200"
    /></button
  >
</h3>
