// demos/vue-demo/src/lib/components/ui/AvatarFallback.vue
<template>
  <span
    ref="ref"
    :class="
      cn(
        'flex h-full w-full items-center justify-center rounded-full bg-muted',
        className
      )
    "
    v-bind="$attrs"
    ><slot></slot
  ></span>
</template>

<script setup lang="ts">
const { className } = defineProps({
  className: { type: String, default: undefined },
});
import { cn } from '@/lib/utils';
</script>

// demos/svelte-demo/src/lib/components/ui/AvatarFallback.svelte
<script lang="ts">
  export let className: string | undefined = undefined;
  $: mergedClass = $$props.class;
  import type { HTMLAttributes } from 'svelte/elements';
  import { cn } from '$lib/utils';

  let ref;
</script>

<span
  bind:this={ref}
  class={cn(
    'flex h-full w-full items-center justify-center rounded-full bg-muted',
    className
  )}
  {...$$restProps}><slot /></span
>
