// demos/vue-demo/src/components/ui/Badge.vue
<script setup lang="ts">
import { cn } from '@/lib/utils';
import { cva } from 'class-variance-authority';

const badgeVariants = cva(
  'inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2',
  {
    variants: {
      variant: {
        default: 'border-transparent bg-primary text-primary-foreground hover:bg-primary/80',
        secondary:
          'border-transparent bg-secondary text-secondary-foreground hover:bg-secondary/80',
        destructive:
          'border-transparent bg-destructive text-destructive-foreground hover:bg-destructive/80',
        outline: 'text-foreground',
      },
    },
    defaultVariants: {
      variant: 'default',
    },
  }
);

interface Props {
  class?: string;
  variant?: 'default' | 'secondary' | 'destructive' | 'outline';
}

const props = withDefaults(defineProps<Props>(), {
  variant: 'default',
});
</script>

<template>
  <div :class="cn(badgeVariants({ variant: props.variant }), props.class)" v-bind="$attrs">
    <slot />
  </div>
</template>

// demos/svelte-demo/src/lib/components/ui/Badge.svelte
<script lang="ts">
  export let variant: string = 'default';
  export let className: string | undefined = undefined;
  $: mergedClass = $$props.class;
  import { cva } from 'class-variance-authority';
  import { cn } from '$lib/utils';
  const badgeVariants = cva(
    'inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2',
    {
      variants: {
        variant: {
          default:
            'border-transparent bg-primary text-primary-foreground hover:bg-primary/80',
          secondary:
            'border-transparent bg-secondary text-secondary-foreground hover:bg-secondary/80',
          destructive:
            'border-transparent bg-destructive text-destructive-foreground hover:bg-destructive/80',
          outline: 'text-foreground',
        },
      },
      defaultVariants: {
        variant: 'default',
      },
    }
  );
</script>

<div
  {...$$restProps}
  class={cn(
    badgeVariants({
      variant,
    }),
    className
  )}
>
  <slot />
</div>
