// demos/vue-demo/src/lib/components/ui/CardDescription.vue
<template>
  <div
    ref="ref"
    :class="cn('text-sm text-muted-foreground', className)"
    v-bind="$attrs"
  >
    <slot></slot>
  </div>
</template>

<script setup lang="ts">
const { className } = defineProps({
  className: { type: String, default: undefined },
});
import { cn } from '@/lib/utils';
</script>

// demos/svelte-demo/src/lib/components/ui/CardDescription.svelte
<script lang="ts">
  export let className: string | undefined = undefined;
  $: mergedClass = $$props.class;
  import type { HTMLAttributes } from 'svelte/elements';
  import { cn } from '$lib/utils';

  let ref;
</script>

<div
  bind:this={ref}
  {...$$restProps}
  class={cn('text-sm text-muted-foreground', mergedClass || className)}
>
  <slot />
</div>
