// demos/vue-demo/src/components/ui/DialogDescription.vue
<script setup lang="ts">
import { ref } from 'vue';
import { cn } from '@/lib/utils';
// import { X } from 'lucide-vue-next'; // Not used in fallback template

interface Props {
  class?: string;
}

const props = defineProps<Props>();

const elementRef = ref<HTMLParagraphElement | null>(null);

defineExpose({ elementRef });
</script>

<template>
  <p ref="elementRef" :class="cn('text-sm text-muted-foreground', props.class)" v-bind="$attrs">
    <slot />
  </p>
</template>

// demos/svelte-demo/src/lib/components/ui/DialogDescription.svelte
<script lang="ts">
import { cn } from "$lib/utils";
import type { HTMLAttributes } from "svelte/elements";
import { X } from "lucide-svelte";

interface Props extends HTMLAttributes<HTMLParagraphElement> {
  class?: string;
  ref?: HTMLParagraphElement | null;
}

let { class: className, ref = $bindable(null), children, ...restProps }: Props = $props();
</script>

<p bind:this={ref} class={cn("text-sm text-muted-foreground", className)} {...restProps}>
  {@render children?.()}
</p>
