// demos/vue-demo/src/lib/components/ui/Input.vue
<template>
  <input
    :type="type"
    ref="ref"
    :class="
      cn(
        'flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-base ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium file:text-foreground placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 md:text-sm',
        className
      )
    "
    v-bind="$attrs"
  />
</template>

<script setup lang="ts">
const { className, type } = defineProps({
  className: { type: String, default: undefined },
  type: { type: String, default: 'text' },
});
import { cn } from '@/lib/utils';
</script>

// demos/svelte-demo/src/lib/components/ui/Input.svelte
<script lang="ts">
  export let className: string | undefined = undefined;
  $: mergedClass = $$props.class;
  export let type: string = 'text';
  export let disabled: boolean = false;
  import type { HTMLInputAttributes } from 'svelte/elements';
  import { cn } from '$lib/utils';

  let ref;
</script>

<input
  {type}
  bind:this={ref}
  {...$$restProps}
  class={cn(
    'flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-base ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium file:text-foreground placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 md:text-sm',
    className
  )}
/>
