// demos/vue-demo/src/lib/components/ui/Progress.vue
<template>
  <div
    ref="ref"
    :class="
      cn(
        'relative h-4 w-full overflow-hidden rounded-full bg-secondary',
        className
      )
    "
    v-bind="$attrs"
  >
    <div
      class="h-full w-full flex-1 bg-primary transition-all"
      :style="{ transform: `translateX(-${100 - (value || 0)}%)` }"
    >
      <slot></slot>
    </div>
  </div>
</template>

<script setup lang="ts">
const { className, value } = defineProps({
  className: { type: String, default: undefined },
  value: { type: String, default: undefined },
});
import { cn } from '@/lib/utils';
</script>

// demos/svelte-demo/src/lib/components/ui/Progress.svelte
<script lang="ts">
  export let className: string | undefined = undefined;
  $: mergedClass = $$props.class;
  export let value: string | undefined = undefined;
  import type { HTMLAttributes } from 'svelte/elements';
  import { cn } from '$lib/utils';

  function stringifyStyles(stylesObj) {
    let styles = '';
    for (let key in stylesObj) {
      const dashedKey = key.replace(/[A-Z]/g, function (match) {
        return '-' + match.toLowerCase();
      });
      styles += dashedKey + ':' + stylesObj[key] + ';';
    }
    return styles;
  }

  let ref;
</script>

<div
  bind:this={ref}
  class={cn(
    'relative h-4 w-full overflow-hidden rounded-full bg-secondary',
    className
  )}
  {...$$restProps}
>
  <div
    style={stringifyStyles({
      transform: `translateX(-${100 - (value || 0)}%)`,
    })}
    class="h-full w-full flex-1 bg-primary transition-all"
  >
    <slot />
  </div>
</div>
