// demos/vue-demo/src/lib/components/ui/Separator.vue
<template>
  <div
    ref="ref"
    :decorative="decorative"
    :orientation="orientation"
    :class="
      cn(
        'shrink-0 bg-border',
        orientation === 'horizontal' ? 'h-[1px] w-full' : 'h-full w-[1px]',
        className
      )
    "
    v-bind="$attrs"
  >
    <slot></slot>
  </div>
</template>

<script setup lang="ts">
const { className, decorative, orientation } = defineProps({
  className: { type: String, default: undefined },
  decorative: { type: Boolean, default: false },
  orientation: { type: String, default: 'horizontal' },
});
import { cn } from '@/lib/utils';
</script>

// demos/svelte-demo/src/lib/components/ui/Separator.svelte
<script lang="ts">
  export let className: string | undefined = undefined;
  $: mergedClass = $$props.class;
  export let decorative: boolean = false;
  export let orientation: string = 'horizontal';
  import type { HTMLAttributes } from 'svelte/elements';
  import { cn } from '$lib/utils';

  let ref;
</script>

<div
  bind:this={ref}
  {decorative}
  {orientation}
  class={cn(
    'shrink-0 bg-border',
    orientation === 'horizontal' ? 'h-[1px] w-full' : 'h-full w-[1px]',
    className
  )}
  {...$$restProps}
>
  <slot />
</div>
