// demos/vue-demo/src/lib/components/ui/Slider.vue
<template>
  <div
    ref="ref"
    :class="
      cn('relative flex w-full touch-none select-none items-center', className)
    "
    v-bind="$attrs"
  >
    <div>
      <div><slot></slot></div>
    </div>
    <span><slot></slot></span>
  </div>
</template>

<script setup lang="ts">
const { className } = defineProps({
  className: { type: String, default: undefined },
});
import { cn } from '@/lib/utils';
</script>

// demos/svelte-demo/src/lib/components/ui/Slider.svelte
<script lang="ts">
  import { cn } from '$lib/utils';
  import type { HTMLAttributes } from 'svelte/elements';

  interface Props extends HTMLAttributes<HTMLSpanElement> {
    class?: string;
    ref?: HTMLSpanElement | null;
  }

  let { class: className, ref = $bindable(null), children, ...restProps }: Props = $props();
</script>

<span
  bind:this={ref}
  class={cn('relative flex w-full touch-none select-none items-center', className)}
  {...restProps}
>
  {@render children?.()}
</span>
