// demos/vue-demo/src/lib/components/ui/TableRow.vue
<template>
  <tr
    ref="ref"
    :class="
      cn(
        'border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted',
        className
      )
    "
    v-bind="$attrs"
  >
    <slot></slot>
  </tr>
</template>

<script setup lang="ts">
const { className } = defineProps({
  className: { type: String, default: undefined },
});
import { cn } from '@/lib/utils';
</script>

// demos/svelte-demo/src/lib/components/ui/TableRow.svelte
<script lang="ts">
  export let className: string | undefined = undefined;
  $: mergedClass = $$props.class;
  import type { HTMLAttributes } from 'svelte/elements';
  import { cn } from '$lib/utils';

  let ref;
</script>

<tr
  bind:this={ref}
  {...$$restProps}
  class={cn(
    'border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted',
    className
  )}><slot /></tr
>
