// demos/vue-demo/src/lib/components/ui/TableCell.vue
<template>
  <td
    ref="ref"
    :class="cn('p-4 align-middle [&:has([role=checkbox])]:pr-0', className)"
    v-bind="$attrs"
  >
    <slot></slot>
  </td>
</template>

<script setup lang="ts">
const { className } = defineProps({
  className: { type: String, default: undefined },
});
import { cn } from '@/lib/utils';
</script>

// demos/svelte-demo/src/lib/components/ui/TableCell.svelte
<script lang="ts">
  export let className: string | undefined = undefined;
  $: mergedClass = $$props.class;
  import type { HTMLAttributes } from 'svelte/elements';
  import { cn } from '$lib/utils';

  let ref;
</script>

<td
  bind:this={ref}
  {...$$restProps}
  class={cn('p-4 align-middle [&:has([role=checkbox])]:pr-0', className)}
  ><slot /></td
>
