// demos/vue-demo/src/components/ui/table/TableHeader.vue
<script setup lang="ts">
import { ref } from 'vue';
import { cn } from '@/lib/utils';

interface Props {
  class?: string;
}

const props = defineProps<Props>();
const elementRef = ref<HTMLTableSectionElement | null>(null);
defineExpose({ elementRef });
</script>

<template>
  <thead ref="elementRef" :class="cn('[&_tr]:border-b', props.class)" v-bind="$attrs">
    <slot />
  </thead>
</template>

// demos/svelte-demo/src/lib/components/ui/TableHeader.svelte
<script lang="ts">
  export let className: string | undefined = undefined;
  $: mergedClass = $$props.class;
  import type { HTMLAttributes } from 'svelte/elements';
  import { cn } from '$lib/utils';

  let ref;
</script>

<thead
  bind:this={ref}
  {...$$restProps}
  class={cn('[&_tr]:border-b', mergedClass || className)}><slot /></thead
>
