// demos/vue-demo/src/components/ui/table/TableRow.vue
<script setup lang="ts">
import { ref } from 'vue';
import { cn } from '@/lib/utils';

interface Props {
  class?: string;
}

const props = defineProps<Props>();
const elementRef = ref<HTMLTableRowElement | null>(null);
defineExpose({ elementRef });
</script>

<template>
  <tr ref="elementRef" :class="cn('border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted', props.class)" v-bind="$attrs">
    <slot />
  </tr>
</template>

// demos/svelte-demo/src/lib/components/ui/TableRow.svelte
<script lang="ts">
  export let className: string | undefined = undefined;
  $: mergedClass = $$props.class;
  import type { HTMLAttributes } from 'svelte/elements';
  import { cn } from '$lib/utils';

  let ref;
</script>

<tr
  bind:this={ref}
  {...$$restProps}
  class={cn(
    'border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted',
    className
  )}><slot /></tr
>
