// demos/vue-demo/src/lib/components/ui/Table.vue
<template>
  <div class="relative w-full overflow-auto">
    <table
      ref="ref"
      :class="cn('w-full caption-bottom text-sm', className)"
      v-bind="$attrs"
    >
      <slot></slot>
    </table>
  </div>
</template>

<script setup lang="ts">
const { className } = defineProps({
  className: { type: String, default: undefined },
});
import { cn } from '@/lib/utils';
</script>

// demos/svelte-demo/src/lib/components/ui/Table.svelte
<script lang="ts">
  export let className: string | undefined = undefined;
  $: mergedClass = $$props.class;
  import type { HTMLAttributes } from 'svelte/elements';
  import { cn } from '$lib/utils';

  let ref;
</script>

<div class="relative w-full overflow-auto">
  <table
    bind:this={ref}
    {...$$restProps}
    class={cn('w-full caption-bottom text-sm', mergedClass || className)}
  >
    <slot />
  </table>
</div>
