// demos/svelte-demo/src/lib/components/ui/table/TableHeader.svelte
<script lang="ts">
  import { cn } from "$lib/utils";
  import type { HTMLAttributes } from "svelte/elements";

  interface Props extends HTMLAttributes<HTMLTableSectionElement> {
    class?: string;
    ref?: HTMLTableSectionElement | null;
  }

  let { class: className, ref = $bindable(null), children, ...restProps }: Props = $props();
</script>

<thead bind:this={ref} class={cn("[&_tr]:border-b", className)} {...restProps}>
  {@render children?.()}
</thead>

// demos/vue-demo/src/components/ui/table/TableHeader.vue
<script setup lang="ts">
import { ref } from 'vue';
import { cn } from '@/lib/utils';

interface Props {
  class?: string;
}

const props = defineProps<Props>();
const elementRef = ref<HTMLTableSectionElement | null>(null);
defineExpose({ elementRef });
</script>

<template>
  <thead ref="elementRef" :class="cn('[&_tr]:border-b', props.class)" v-bind="$attrs">
    <slot />
  </thead>
</template>
