// demos/svelte-demo/src/lib/components/ui/Table.svelte
<script lang="ts">
  export let className: string | undefined = undefined;
  $: mergedClass = $$props.class;
  import type { HTMLAttributes } from 'svelte/elements';
  import { cn } from '$lib/utils';

  let ref;
</script>

<div class="relative w-full overflow-auto">
  <table
    bind:this={ref}
    {...$$restProps}
    class={cn('w-full caption-bottom text-sm', mergedClass || className)}
  >
    <slot />
  </table>
</div>

// demos/vue-demo/src/components/ui/table/Table.vue
<script setup lang="ts">
import { ref } from 'vue';
import { cn } from '@/lib/utils';

interface Props {
  class?: string;
}

const props = defineProps<Props>();
const elementRef = ref<HTMLTableElement | null>(null);
defineExpose({ elementRef });
</script>

<template>
  <div class="relative w-full overflow-auto">
    <table ref="elementRef" :class="cn('w-full caption-bottom text-sm', props.class)" v-bind="$attrs">
      <slot />
    </table>
  </div>
</template>
