// demos/svelte-demo/src/lib/components/ui/TableHead.svelte
<script lang="ts">
  export let className: string | undefined = undefined;
  $: mergedClass = $$props.class;
  import type { HTMLAttributes } from 'svelte/elements';
  import { cn } from '$lib/utils';

  let ref;
</script>

<th
  bind:this={ref}
  {...$$restProps}
  class={cn(
    'h-12 px-4 text-left align-middle font-medium text-muted-foreground [&:has([role=checkbox])]:pr-0',
    className
  )}><slot /></th
>

// demos/vue-demo/src/components/ui/table/TableHead.vue
<script setup lang="ts">
import { ref } from 'vue';
import { cn } from '@/lib/utils';

interface Props {
  class?: string;
}

const props = defineProps<Props>();
const elementRef = ref<HTMLTableCellElement | null>(null);
defineExpose({ elementRef });
</script>

<template>
  <th ref="elementRef" :class="cn('h-12 px-4 text-left align-middle font-medium text-muted-foreground [&:has([role=checkbox])]:pr-0', props.class)" v-bind="$attrs">
    <slot />
  </th>
</template>
