// demos/svelte-demo/src/lib/components/ui/table/TableHead.svelte
<script lang="ts">
  import { cn } from "$lib/utils";
  import type { HTMLThAttributes } from "svelte/elements";

  interface Props extends HTMLThAttributes {
    class?: string;
    ref?: HTMLTableCellElement | null;
  }

  let { class: className, ref = $bindable(null), children, ...restProps }: Props = $props();
</script>

<th bind:this={ref} class={cn("h-12 px-4 text-left align-middle font-medium text-muted-foreground [&:has([role=checkbox])]:pr-0", className)} {...restProps}>
  {@render children?.()}
</th>

// demos/vue-demo/src/components/ui/table/TableHead.vue
<script setup lang="ts">
import { ref } from 'vue';
import { cn } from '@/lib/utils';

interface Props {
  class?: string;
}

const props = defineProps<Props>();
const elementRef = ref<HTMLTableCellElement | null>(null);
defineExpose({ elementRef });
</script>

<template>
  <th ref="elementRef" :class="cn('h-12 px-4 text-left align-middle font-medium text-muted-foreground [&:has([role=checkbox])]:pr-0', props.class)" v-bind="$attrs">
    <slot />
  </th>
</template>
