// demos/svelte-demo/src/lib/components/ui/table/TableCaption.svelte
<script lang="ts">
  import { cn } from "$lib/utils";
  import type { HTMLAttributes } from "svelte/elements";

  interface Props extends HTMLAttributes<HTMLTableCaptionElement> {
    class?: string;
    ref?: HTMLTableCaptionElement | null;
  }

  let { class: className, ref = $bindable(null), children, ...restProps }: Props = $props();
</script>

<caption bind:this={ref} class={cn("mt-4 text-sm text-muted-foreground", className)} {...restProps}>
  {@render children?.()}
</caption>

// demos/vue-demo/src/components/ui/table/TableCaption.vue
<script setup lang="ts">
import { ref } from 'vue';
import { cn } from '@/lib/utils';

interface Props {
  class?: string;
}

const props = defineProps<Props>();
const elementRef = ref<HTMLTableCaptionElement | null>(null);
defineExpose({ elementRef });
</script>

<template>
  <caption ref="elementRef" :class="cn('mt-4 text-sm text-muted-foreground', props.class)" v-bind="$attrs">
    <slot />
  </caption>
</template>
