// demos/svelte-demo/src/lib/components/ui/CardContent.svelte
<script lang="ts">
  export let className: string | undefined = undefined;
  $: mergedClass = $$props.class;
  import type { HTMLAttributes } from 'svelte/elements';
  import { cn } from '$lib/utils';

  let ref;
</script>

<div
  bind:this={ref}
  {...$$restProps}
  class={cn('p-6 pt-0', mergedClass || className)}
>
  <slot />
</div>

// demos/vue-demo/src/components/ui/card/CardContent.vue
<script setup lang="ts">
import { ref } from 'vue';
import { cn } from '@/lib/utils';

interface Props {
  class?: string;
}

const props = defineProps<Props>();

const elementRef = ref<HTMLDivElement | null>(null);

defineExpose({ elementRef });
</script>

<template>
  <div ref="elementRef" :class="cn('p-6 pt-0', props.class)" v-bind="$attrs">
    <slot />
  </div>
</template>
